# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Basic_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=200)),
                ('image_label_count', models.IntegerField(default=0)),
                ('image_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Label_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_label_count', models.IntegerField(default=0)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_image_id', to='SA_Label_System.Image_Basic_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Label_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_score', models.FloatField(default=-1)),
                ('label_time', models.DateTimeField()),
                ('base_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_image_id', to='SA_Label_System.Image_Basic_Info')),
                ('label_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_image_id', to='SA_Label_System.Image_Basic_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Label_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_time', models.DateTimeField()),
                ('group_num', models.IntegerField(default=1)),
                ('project_images_num', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_images_num', models.IntegerField(default=1)),
                ('group_labeled_num', models.IntegerField(default=0)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_project_name', to='SA_Label_System.Label_Project')),
            ],
        ),
        migrations.CreateModel(
            name='User_Basic_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=64)),
                ('email_address', models.CharField(max_length=128)),
                ('label_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_select', models.IntegerField(default=1)),
                ('project_select', models.CharField(default='.', max_length=200)),
                ('user_basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_user_basic_info', to='SA_Label_System.User_Basic_Info')),
            ],
        ),
        migrations.AddField(
            model_name='image_label_info',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SA_Label_System.User_Basic_Info'),
        ),
        migrations.AddField(
            model_name='image_label_count',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_user_id', to='SA_Label_System.User_Basic_Info'),
        ),
        migrations.AddField(
            model_name='image_basic_info',
            name='image_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibi_image_group', to='SA_Label_System.Project_Group'),
        ),
        migrations.AddField(
            model_name='image_basic_info',
            name='image_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibi_image_project', to='SA_Label_System.Label_Project'),
        ),
    ]
